project:
  type: website
  output-dir: docs


website:
  title: "Marisol's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - Analysis_Walkthrough.qmd
      - my_paper.qmd
      - my_article.qmd
      - href: https://drive.google.com/file/d/1NTB4ZayLZGWUqhfckfSl4GzHkVMPFfuf/view?usp=sharing
        text: Resume
  page-footer: 
    left: "Copyright 2022, Marisol Cabrera" 
    right: 
      - icon: github
        href: https://github.com/mcabrera86

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



