---
title: "My Publsihed Written Work"
---

Here is a past article I wrote that was published on [The GW Local](https://thegwlocal.com/), GW's Lifestyle news blog.

# Want To Go to the Movies? Here's What to Watch This Season

**By Marisol Cabrera**

As the temperature cools and the leaves turn brown, I know my favorite season is just around the corner. No, not Fall. I'm talking about Oscar season, a period in the Fall and Winter where movie studios release films they hope to push for the Academy Awards in March. 

Due to the pandemic delaying film production for the past two years, this Oscar season is more jam packed than ever. To make your movie-going decisions less overwhelming, let me break down some of the most highly anticipated upcoming releases this season.

## **No Time to Die**

In Daniel Craig's last outing as everyone's favorite secret agent, James Bond, *No Time to Die* ends Craig's run with a bang as some critics call it the best performance of Bond in the franchise's history. The film picks up where the previous Bond film, *Spectre*, left off. Agent Bond, no longer in active service, is thrown back into action after a friend from the CIA asks for him to go on one last mission to save a kidnapped scientist. As Bond discovers the work of a mysterious villain, he realizes his last outing will be anything but safe.

**Watch if you:** are in the mood for an action-filled thriller that will also pack an emotional punch!

**Release date:** out now!

## **Dune**

This ambitious adaptation of Frank Herbert's science fiction novel is a film meant to be seen on the big screen. The intense music, visuals, and performances from a star-studded cast including Timothée Chalamet, Jason Momoa, Oscar Issac, and Zendaya makes *Dune* not just a movie you see, but an experience. Set far in the future, the story revolves around the young Paul Atreides, played by Chalamet, son of a Duke who is the ruler of Caladan (just one planet in a galaxy ruled by an Emperor). As Paul's family is given more power, chaos breaks out and Paul quickly learns his destiny is much greater than he could have ever imagined. While you can watch *Dune* on HBO Max, watch it in the theater for the best possible experience! 

**Watch if you:** are a fan of *Star Wars* and *Game of Thrones...* or just Timothée Chalamet!

**Release date:** out now!

## **The French Dispatch**

Wes Anderson's comedy-drama anthology, *The French Dispatch*, features Anderson's trademark meticulous visual style as well as an overwhelmingly talented cast including Bill Murray, Owen Wilson, Elisabeth Moss, Frances McDormand, and once again Timothée Chalamet. The film is a "love letter to journalists," telling several short stories based around a fictional American newspaper set in a fictional 20th-century French city. Anderson's idiosyncratic filmmaking style, coupled with the film's unique story structure makes *The French Dispatch* unlike any film currently in theaters. 

**Watch if you:** like aesthetically pleasing films with eccentric characters... or just Timothée Chalamet!

**Release date:** out now!

## **Eternals**

The Marvel Cinematic Universe is back in full gear with the release of this jam-packed superhero film, but with new faces both in front of and behind the camera. Coming off the heels of her Best Picture and Best Director wins at the Oscars, Chloé Zhao gives a fresh take on the Marvel film franchise as Angelina Jolie, Richard Madden, Kit Harington, Kumail Nanjiani, Gemma Chan, and too many others to list, star in her new film. Based on the immortal alien race from the Marvel comics, *Eternals* starts off after the events of *Avengers: Endgame*. The Eternals, who have stayed hidden on Earth, are forced to come together to protect the world from the Deviants, their oldest and deadliest enemy.

**Watch if you:** want that epic Marvel movie feel but with fresh, new characters!

**Release date:** Nov. 5!

## **Last Night in Soho**

In this psychological thriller, director Edgar Wright combines horror and time travel with all the flash and style of the 1960s in London. The film begins in the modern day and tells the story of Ellie, a music and fashion lover who travels to London to study fashion design. Feeling ostracized by her peers, Ellie moves out of her dorms and into an apartment where she begins to have vivid dreams of the '60s in London and an up-and-coming singer named Sandie, which starts to blend with her everyday life. At first enthralled by these visions, Ellie discovers the darkness of the past and why some things should stay hidden.

**Watch if you:** want a stylish and eerie psychological thriller to continue the spooky season!

**Release date:** Out now!

## **Spencer**

Kristen Stewart gives the performance of her career in *Spencer* as the late Diana, Princess of Wales, and has already garnered Oscar buzz for the role. In addition to Stewart's performance, the film is also praised for its beautiful cinematography and regal production design. The story takes place over just a few days, providing a fictional account of the events that took place over the Christmas holidays at the Queen's estate, the last Christmas before Princess Diana and Prince Charles famously separated.  

**Watch if you:** miss *The Crown* and want to see a more Diana-centered story!

**Release date:** Nov. 5!

## **House of Gucci**

Lady Gaga and Adam Driver lead this jaw-dropping crime drama inspired by true events about the famous Gucci fashion house. In roles worthy of icon status, Gaga and Driver bring the dramatic flair and fashion worthy of the Gucci name. The film takes place over three decades, depicting the scandal, romance, and murder of the then head of the fashion house Maurisio Gucci (played by Driver) who is killed by his ex-wife Patrizia Reggiani (played by Gaga). 

**Watch if you:** want to see Lady Gaga speak with an Italian accent and wear stunning outfits!

**Release date:** Nov. 24!

## **Encanto**

With music from Hamilton's Lin-Manuel Miranda, *Encanto* is destined to become the next in Disney's long line of iconic animated musicals. Set in the magical mountains of Colombia, the Madrigal family all have their own special powers, with the sole exception of ordinary Mirabel. However, after learning that her family's magic is in danger, Mirabel realizes that she is their only hope to save it. Scheduled to premiere Thanksgiving weekend, Encanto is a perfect holiday film for the whole family.

**Watch if you:** want that classic Disney feel-good spirit that will tug at your heartstrings!

**Release date:** Nov. 24!

\
