---
title: "My Written Work"
---

Here is a paper I had to write for my Media Law course at GW that contextualized legal topics we discussed in class through a real world example.

Marisol Cabrera

SMPA 2173

Professor Ward

5 October 2021

Real World Assignment

For my first \"Real World\" writing assignment I chose a Bloomberg Law article titled, \"[Nunes Libel Case Raises Actual-Malice Liability for Retweets](https://news.bloomberglaw.com/us-law-week/actual-malice-liability-for-retweets-raised-by-nunes-libel-case)\" by Kyle Jahner and was published recently on September 20, 2021.

In 2019, Californian Representative Devin Nunes filed a libel suit, *Nunes v.
Lizza*, against Hearst Magazine Media Inc and writer Ryan Lizza in which Lizza made accusations about the use of undocumented workers at Nunes' family's dairy farm. Lizza retweeted this article after the libel suit was filed and before the Judge's ruling came. Nunes believed Lizza retweeting a story undergoing a libel suit was grounds for actual malice as Lizza did not include the context of Nunes' denial and the pending suit. In Nunes\' mind this fulfilled the \"reckless disregard for the truth'' aspect of actual malice, a standard set in *New York Times v.
Sullivan*. On the district level the judge dismissed all of Nunes' claims. However, in 2021 the U.S. Court of Appeals for the Eighth Circuit gave a ruling that while again stated Nunes failed to prove all elements in the libel suit, the court frowned upon Lizza\'s decision to retweet the article after the libel suit was filed. This decision by the court signals a potential rehauling of the single publication rule in the light of a new digital age, specifically in relation to social media, and in this case, retweets.

In terms of whether or not Lizza
acted with actual malice, I believe there are arguments to both sides. \"Actual
malice\" is defined in *New York Times v. Sullivan* as publishing something \"with knowledge that it was false or with reckless disregard of whether it was false or not.\" As Lizza\'s accused act of actual malice stems from his retweet --- when he was aware of Nunes\' denial and suit and did not acknowledge it--- the heart of this issue is whether or not retweeting this story should fulfill the \"publishing\" element of actual malice set in *New York Times v. Sullivan*.

On one hand, the single publication rule states that plaintiffs in a libel case cannot file multiple libel suits even in the case of republication from the same outlet. Lizza\'s retweet was of the same story Nunes originally filed his libel suit for, so on the surface it appears clear that the single publication rule would apply and Nunes would be unable to file a separate claim accusing Lizza of actual malice. However the single publication rule no longer applies when the content of the news story
changes to include a new libel. Lizza\'s retweet came two years after the publication of the original story and Nunes\' denial and suit could be considered the new content to no longer make the single publication rule valid. Although it is questionable whether or not someone\'s denial of unflattering claims made against them is significant enough to qualify as new libel. Nunes\' denial could reasonably be expected by readers of the story.

It can also be argued that the single publication rule should be dismissed if the second publication reaches a new audience. In its decision the appellate court which ruled on the Nunes case, gave the example of an evening edition of a morning newspaper qualifying as a new publication since the two editions could reasonably be assumed to reach two different audiences. In Lizza\'s case, his retweet of the originally printed Esquire article to the online version, two years after the publication, could theoretically be the new audience the court was talking about to be considered a new publication. However, this case is not as clear as the morning to night edition of a newspaper since Lizza\'s linking of this story, even after a lengthy amount of time, was not targeting a brand new audience but reminding the public of a story that has become relevant again.

Overall, I would decide that Lizza did not act with actual malice and that retweeting a story as Lizza did is not a new publication. In an increasingly digital world, journalists have found ways to use social media to best share their work with the public, and in return more and more of the public rely on social media to aggregate relevant and important news articles to consume. I believe if the court were to side with Nunes in this case and rule that Lizza acted with actual malice, there could be a chilling effect on reporters and their willingness to share their work on Twitter. While this might not seem like a big deal, digital clicks and views weigh greatly on which news stories are considered successful and are covered more often versus which are buried and not promoted. While I agree that there is some gray area in Lizza\'s case, I think media outlets should be given the benefit of the doubt in unclear cases due to the high priority placed on the freedom of the press, especially related to political matters.

References

*New York Times Co. v. Sullivan*, 376 U.S. 254, 84 S. Ct. 710 (1964)

*Nunes v. Lizza*, 486 F. Supp. 3d 1267 (N.D. Iowa 2020)

Ross, Susan Dente, et al. *The Law of Journalism and Mass Communication*. Seventh edition ed.,

CQ Press, an Imprint of Sage Publications, Inc., 2020.
