---
title: "Portfolio"
---

Here are some videos I've made for GW-TV, my university's student-run TV station, and other projects I've made as a journalism student at the George Washington University.

## News Episodes

Here are two episodes from GWeek, GW-TV's campus news program, which covers topical events ranging from on campus to international news.

[GWeek 11/16](https://www.youtube.com/watch?time_continue=1&v=QKa5drhbiGg&feature=emb_logo) - Roles: Executive Producer, Editor, Co-Director

[GWeek 10/14](https://www.youtube.com/watch?time_continue=1&v=QKa5drhbiGg&feature=emb_logo) - Roles: Executive Producer, Editor, Co-Director

## Promo Videos

[Obama PSA Project](https://vimeo.com/534516084) - Roles: Editor, Producer \| created for a video production class at GW, meant to practice video editing skills in service of promoting a message.

[GW Balance Promo](https://vimeo.com/642044051) - Roles: Co-Editor, Co-Producer, Co-Director \| created for a web production class at GW, meant to practice filming and editing skills in service of promoting an organization.
